//user login types
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//user register types
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

//user loading
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

//error types
export const AUTH_ERRORS = "AUTH_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = " CLEAR_ERRORS";

//get dishes types
export const GET_DISHES_REQUEST = "GET_DISHES_REQUEST";
export const GET_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const GET_DISHES_FAILURE = "GET_DISHES_FAILURE";

//add dishes types
export const ADD_DISH_REQUEST = "ADD_DISH_REQUEST";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const ADD_DISH_FAILURE = "ADD_DISH_FAILURE";

//edit dishes types
export const EDIT_DISH_REQUEST = "EDIT_DISH_REQUEST";
export const EDIT_DISH_SUCCESS = "EDIT_DISH_SUCCESS";
export const EDIT_DISH_FAILURE = "EDIT_DISH_FAILURE";

//delete dishes types
export const DELETE_DISH_REQUEST = "DELETE_DISH_REQUEST";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const DELETE_DISH_FAILURE = "DELETE_DISH_FAILURE";

//cart types
export const ADD_DISH_TO_CART = "ADD_DISH_TO_CART";
export const DELETE_DISH_FROM_CART = "DELETE_DISH_FROM_CART";
export const SUBMIT_ORDER_OF_CART_REQUEST = "SUBMIT_ORDER_OF_CART_REQUEST";
export const SUBMIT_ORDER_OF_CART_SUCCESS = "SUBMIT_ORDER_OF_CART_SUCCESS";
export const SUBMIT_ORDER_OF_CART_FAILURE = "SUBMIT_ORDER_OF_CART_FAILURE";

export const CHANGE_QUANTITY_OF_DISH_CART = "CHANGE_QUANTITY_OF_DISH_CART";

export const LOAD_DISH_TO_CART = "LOAD_DISH_TO_CART";
export const CLEAR_CART = "CLEAR_CART";

//success message types

export const GET_RESPONSE_MESSAGE = "GET_RESPONSE_MESSAGE";
export const CLEAR_RESPONSE_MESSAGE = "CLEAR_RESPONSE_MESSAGE";
